# Generated by Django 2.2 on 2019-09-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.IntegerField(null=True)),
                ('visible', models.BooleanField(default=False)),
                ('resume_way', models.CharField(blank=True, max_length=20, null=True)),
                ('resume_way2', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', '男'), ('f', '女')], max_length=1, null=True)),
                ('birth_year', models.CharField(blank=True, choices=[('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008')], max_length=4, null=True)),
                ('birth_month', models.CharField(blank=True, max_length=4, null=True)),
                ('birth_day', models.CharField(blank=True, max_length=4, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('identity', models.CharField(blank=True, max_length=25, null=True)),
                ('age', models.IntegerField(null=True)),
                ('birth_province', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_district', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('qq', models.BigIntegerField(blank=True, null=True)),
                ('residence', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('marriage', models.CharField(blank=True, choices=[('', ''), ('未婚', '未婚'), ('已婚', '已婚'), ('离婚', '离婚')], max_length=10, null=True)),
                ('live_state', models.CharField(blank=True, max_length=10, null=True)),
                ('current_settle_province', models.CharField(blank=True, max_length=10, null=True)),
                ('current_settle_city', models.CharField(blank=True, max_length=10, null=True)),
                ('current_settle_district', models.CharField(blank=True, max_length=10, null=True)),
                ('current_settle_street', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_industry', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_post', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_positon', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_province', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_city', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_district', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_street', models.CharField(blank=True, max_length=50, null=True)),
                ('degree', models.IntegerField(blank=True, choices=[(0, ''), (1, '小学'), (2, '初中'), (3, '高中'), (4, '中专'), (5, '大专'), (6, '本科'), (7, '硕士'), (8, '博士'), (9, '博士后')], null=True)),
                ('major', models.CharField(blank=True, max_length=30, null=True)),
                ('school', models.CharField(blank=True, max_length=30, null=True)),
                ('graduate_time', models.CharField(blank=True, max_length=30, null=True)),
                ('graduate_year', models.IntegerField(blank=True, null=True)),
                ('self_description', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('reserved1', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('reserved2', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('college', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('degree', models.IntegerField(blank=True, choices=[(0, ''), (1, '小学'), (2, '初中'), (3, '高中'), (4, '中专'), (5, '大专'), (6, '本科'), (7, '硕士'), (8, '博士'), (9, '博士后')], null=True)),
                ('edu_type', models.CharField(blank=True, choices=[('', ''), ('统招', '统招'), ('普招', '普招'), ('成招', '成招'), ('非统招', '非统招'), ('其他', '其他')], max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('district', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('instructor', models.CharField(blank=True, max_length=50, null=True)),
                ('instructor_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resumes.Resume')),
            ],
        ),
    ]
