# Generated by Django 2.2 on 2019-10-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='hunting_status',
            field=models.IntegerField(blank=True, choices=[(-1, ''), (0, '在职,不找工作'), (1, '在职,考虑新机会'), (2, '离职,正在找工作')], null=True),
        ),
    ]
