# Generated by Django 2.2 on 2019-12-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_hunting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='callInstanceId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='callJobname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='callPhoneDuration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='callTags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
