# Generated by Django 2.2 on 2020-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_auto_20200325_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.IntegerField(blank=True, null=True)),
                ('col', models.CharField(blank=True, max_length=255, null=True)),
                ('val', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='operator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='step',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
