# Generated by Django 2.2 on 2020-05-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_auto_20200325_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.IntegerField(blank=True, default=0, null=True)),
                ('kind', models.CharField(blank=True, max_length=255, null=True)),
                ('sort', models.IntegerField(blank=True, default=0, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_called',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='importer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='birth_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_way',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_way2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='LabelScoreLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('num', models.IntegerField(blank=True, default=0, null=True)),
                ('score', models.IntegerField(blank=True, default=10, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='RESUME_SCORE_LOG', to='resumes.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='LabelScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('val', models.IntegerField(blank=True, default=0, null=True)),
                ('score', models.IntegerField(blank=True, default=10, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='RESUME_SCORE', to='resumes.Resume')),
            ],
        ),
    ]
