# Generated by Django 2.2 on 2020-12-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('resumes', '0008_auto_20201205_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag2',
            name='focusPoint',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tag.FocusPoint'),
        ),
        migrations.AddField(
            model_name='tag2',
            name='itmeInFocusPoint',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tag.ItemInFocusPoint'),
        ),
        migrations.AddField(
            model_name='tag2',
            name='resume',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resumes.Resume'),
        ),
    ]
