# Generated by Django 2.2 on 2020-12-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_auto_20201205_2010'),
    ]

    operations = [
    ]
