# Generated by Django 2.2 on 2020-12-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_auto_20201205_2130'),
    ]

    operations = [
    ]
