# Generated by Django 2.2 on 2020-12-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_posttag2'),
        ('resumes', '0011_auto_20201220_1544'),
        ('smart_analyse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePostMatchScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='companies.Post')),
                ('resume', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resumes.Resume')),
            ],
        ),
    ]
