# Generated by Django 2.2 on 2019-09-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('scale', models.IntegerField(blank=True, default=0, null=True)),
                ('scale2', models.TextField(blank=True, choices=[(0, ''), (1, '0-50'), (2, '50-100'), (3, '100-500'), (4, '500-1000'), (5, '1000-5000'), (6, '5000以上')], null=True)),
                ('registerd_capital', models.IntegerField(blank=True, default=0, null=True)),
                ('founding_time', models.DateField(blank=True, null=True)),
                ('uscc', models.CharField(blank=True, max_length=50, null=True)),
                ('address_province', models.CharField(blank=True, max_length=10, null=True)),
                ('address_city', models.CharField(blank=True, max_length=10, null=True)),
                ('address_district', models.CharField(blank=True, max_length=10, null=True)),
                ('address_street', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('business_licence', models.ImageField(blank=True, null=True, upload_to='')),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('c_type', models.CharField(blank=True, max_length=50, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('area_ptr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('reserved1', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('reserved2', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('p_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('p_feature', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('p_xingzhi', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('level', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('subsidy', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('sum_salary', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('year_yard', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('social_security', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('other_benefit', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('address_province', models.CharField(blank=True, max_length=10, null=True)),
                ('address_city', models.CharField(blank=True, max_length=10, null=True)),
                ('address_district', models.CharField(blank=True, max_length=10, null=True)),
                ('address_street', models.CharField(blank=True, max_length=20, null=True)),
                ('degree', models.IntegerField(blank=True, choices=[(0, ''), (1, '小学'), (2, '初中'), (3, '高中'), (4, '中专'), (5, '大专'), (6, '本科'), (7, '硕士'), (8, '博士'), (9, '博士后')], null=True)),
                ('degree_min', models.IntegerField(blank=True, choices=[(0, ''), (1, '小学'), (2, '初中'), (3, '高中'), (4, '中专'), (5, '大专'), (6, '本科'), (7, '硕士'), (8, '博士'), (9, '博士后')], null=True)),
                ('degree_max', models.IntegerField(blank=True, choices=[(0, ''), (1, '小学'), (2, '初中'), (3, '高中'), (4, '中专'), (5, '大专'), (6, '本科'), (7, '硕士'), (8, '博士'), (9, '博士后')], null=True)),
                ('graduatetime_min', models.IntegerField(blank=True, null=True)),
                ('graduatetime_max', models.IntegerField(blank=True, null=True)),
                ('age_min', models.IntegerField(blank=True, null=True)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('recruit_count', models.IntegerField(blank=True, null=True)),
                ('salary_offer', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('observe_time', models.IntegerField(blank=True, null=True)),
                ('interview_location', models.CharField(blank=True, max_length=30, null=True)),
                ('linkman', models.CharField(blank=True, max_length=10, null=True)),
                ('linkman_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('reserved1', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('reserved2', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('baiying_task_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('baiying_task_id', models.IntegerField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Department')),
            ],
        ),
    ]
