# Generated by Django 2.2 on 2019-11-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_post_resume_latest_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='baiying_talk_done',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
