# Generated by Django 2.2 on 2020-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200325_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='finished',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='address_district',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='address_province',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='address_street',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
