# Generated by Django 2.2 on 2019-09-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('resumes', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=1)),
                ('status', models.IntegerField(choices=[(0, '筛选'), (1, 'AI面试'), (2, '邀约'), (3, '面试'), (4, 'OFFER'), (5, '入职'), (6, '考察'), (7, '回款'), (8, '完成'), (-2, '停止'), (-1, '自增')], default=0)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=50)),
                ('sub_status', models.CharField(max_length=50)),
                ('is_match', models.BooleanField(default=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Post')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.Resume')),
            ],
            options={
                'unique_together': {('post', 'resume')},
            },
        ),
        migrations.CreateModel(
            name='InterviewSub_Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.IntegerField(null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.IntegerField(null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.IntegerField(null=True)),
                ('interview', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interviews.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Payback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.IntegerField(null=True)),
                ('interview', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interviews.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Probation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.IntegerField(null=True)),
                ('interview', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interviews.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='OnDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, '入职确认'), (2, '考察期'), (3, 'finish')], default=0)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Post')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Terminate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_industry', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_post', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_shift', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_notes', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_province', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_city', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_district', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_insurance', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_insurance_schedule', models.CharField(blank=True, max_length=50, null=True)),
                ('interview', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interviews.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Probation_Fail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, max_length=50, null=True)),
                ('probation_sub', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interviews.InterviewSub_Probation')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Payback_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('pm_amount', models.IntegerField(null=True)),
                ('invitor_amount', models.IntegerField(null=True)),
                ('img', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('payback_sub', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interviews.InterviewSub_Payback')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Payback_Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=50, null=True)),
                ('idn', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('cardid', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('mail_address', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('payback_sub', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interviews.InterviewSub_Payback')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Payback_Finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('payback_sub', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interviews.InterviewSub_Payback')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Payback_Baddebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('payback_sub', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interviews.InterviewSub_Payback')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Offer_Agree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('postname', models.CharField(blank=True, max_length=50, null=True)),
                ('certification', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('offer_sub', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interviews.InterviewSub_Offer')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Invite_Disagree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance', models.CharField(blank=True, max_length=50, null=True)),
                ('other', models.CharField(blank=True, max_length=500, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Invite_Agree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('certification', models.CharField(blank=True, max_length=500, null=True)),
                ('attention', models.CharField(blank=True, max_length=500, null=True)),
                ('other', models.CharField(blank=True, max_length=500, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Interview_Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=50, null=True)),
                ('interview_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.InterviewSub_Interview')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSub_Appointment_Agree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('postname', models.CharField(blank=True, max_length=50, null=True)),
                ('certification', models.CharField(blank=True, max_length=50, null=True)),
                ('attention', models.CharField(blank=True, max_length=50, null=True)),
                ('first_impression', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('appointment_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.InterviewSub_Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewLogCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '筛选'), (1, 'AI面试'), (2, '邀约'), (3, '面试'), (4, 'OFFER'), (5, '入职'), (6, '考察'), (7, '回款'), (8, '完成'), (-2, '停止'), (-1, '自增')], default=0)),
                ('passInter', models.BooleanField(default=0)),
                ('result', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.Interview')),
            ],
        ),
    ]
